export { default as HeaderSection } from './HeaderSection/HeaderSection';
export { default as TransformGrowth } from './LandinPage/TransformGrowth/TransformGrowth';
export { default as HowLendoWorks } from './LandinPage/HowLendoWorks/HowLendoWorks';
export { default as NewToInvesting } from './LandinPage/NewToInvesting/NewToInvesting';
export { default as OurCommitment } from './LandinPage/OurCommitment/OurCommitment';
export { default as AppGrade } from './LandinPage/AppGrade/AppGrade';
export { default as Faqs } from './Shared/Faqs/Faqs';
export { default as CopyRights } from './LandinPage/CopyRights/CopyRights';
export { default as ThemeSwitcher } from './ThemeSwitcher/ThemeSwitcher';
